name: Compile Exchange Rates and Cache Locally

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    # At minute 0 past every 4th hour.
    # https://crontab.guru/#0_*/4_*_*_*
    - cron: "0 */4 * * *"

jobs:
  CompileExchangeRates:
    
    runs-on: ubuntu-latest
    
    steps:
      - env:
          EXCHANGERATESAPI_IO_APIKEY: ${{secrets.EXCHANGERATESAPI_IO_APIKEY}}
          EXCHANGERATESAPI_IO_BASESYMBOL: ${{secrets.EXCHANGERATESAPI_IO_BASESYMBOL}}
        run: >-
          curl \
            --request GET 'https://api.apilayer.com/exchangerates_data/lates?base=${{env.EXCHANGERATESAPI_IO_BASESYMBOL}}' \
            --header 'apiKey: ${{env.EXCHANGERATESAPI_IO_APIKEY}}' \
            -o "data/rates.json"
            
      - uses: actions/deploy-pages@v1
        with:
          name: gituhub-pages
          path: data/


  PublishToGithubPages:
    
    runs-on: ubuntu-latest
    
    needs: 
      - CompileExchangeRates

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1